const mongoose = require("mongoose");

const ticketSchema = new mongoose.Schema(
  {
    // =========================
    // BASIC TICKET INFORMATION
    // =========================

    title: {
      type: String,
      required: [true, "Title is required"],
      trim: true,
    },

    description: {
      type: String,
      required: [true, "Description is required"],
    },

    // =========================
    // TICKET STATUS
    // =========================

    status: {
      type: String,
      enum: [
        "open",
        "in-progress",
        "waiting-for-user",
        "resolved",
        "closed",
      ],
      default: "open",
    },

    // =========================
    // PRIORITY
    // =========================

    priority: {
      type: String,
      enum: ["low", "medium", "high", "urgent"],
      default: "medium",
    },

    // =========================
    // CATEGORY
    // =========================

    category: {
      type: String,
      enum: [
        "hardware",
        "software",
        "network",
        "access",
        "billing",
        "other",
      ],
      default: "other",
    },

    // =========================
    // AI SUMMARY
    // =========================

    // One-line summary generated by Groq
    // when the ticket is created.
    aiSummary: {
      type: String,
      default: "",
      trim: true,
    },

    // =========================
    // AI CONFIDENCE
    // =========================

    // AI confidence score for the classification.
    // Value is between 0 and 1.
    aiConfidence: {
      type: Number,
      min: 0,
      max: 1,
      default: 0,
    },

    // =========================
    // AI REASON
    // =========================

    // Short explanation of why AI selected
    // the category and priority.
    aiReason: {
      type: String,
      default: "",
      trim: true,
    },

    // =========================
    // TICKET CREATOR
    // =========================

    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },

    // =========================
    // TEAM ASSIGNMENT
    // =========================

    // Team to which the ticket is routed.
    assignedTeam: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Team",
      default: null,
    },

    // =========================
    // AGENT ASSIGNMENT
    // =========================

    // Specific agent handling the ticket.
    assignedAgent: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      default: null,
    },

    // =========================
    // RESOLUTION
    // =========================

    // Explanation of how the issue was solved.
    resolution: {
      type: String,
      trim: true,
      default: "",
    },

    // =========================
    // RESOLUTION INFORMATION
    // =========================

    // When the ticket was marked as resolved.
    resolvedAt: {
      type: Date,
      default: null,
    },

    // Agent who resolved the ticket.
    resolvedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      default: null,
    },

    // =========================
    // CLOSED INFORMATION
    // =========================

    // When the ticket was finally closed.
    closedAt: {
      type: Date,
      default: null,
    },

    // Agent/admin who closed the ticket.
    closedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      default: null,
    },
  },

  // Automatically creates:
  // createdAt
  // updatedAt
  { timestamps: true }
);

// =====================================
// INDEXES
// =====================================

// User's tickets
ticketSchema.index({
  createdBy: 1,
});

// Team's tickets
ticketSchema.index({
  assignedTeam: 1,
});

// Agent's assigned tickets
ticketSchema.index({
  assignedAgent: 1,
});

// Team + status is useful for the team dashboard
ticketSchema.index({
  assignedTeam: 1,
  status: 1,
});

// Team + priority is useful for filtering urgent tickets
ticketSchema.index({
  assignedTeam: 1,
  priority: 1,
});

module.exports = mongoose.model("Ticket", ticketSchema);